/**
 * Top 100 CS University sources — pre-configured with known project showcase URLs.
 *
 * Sources include capstone project pages, senior thesis archives, CS department
 * project showcases, and CS department homepages for universities where dedicated
 * project pages are not publicly indexed.
 */

import type { UniversitySource } from '../../../types/search.types';

/**
 * Pre-configured university sources for the crawler.
 * Universities marked `requiresResearch: true` have only their CS department
 * homepage listed — their project showcase URLs need manual discovery.
 */
export const UNIVERSITY_SOURCES: UniversitySource[] = [
  // ── Top 10 ──────────────────────────────────────────────────────────────
  {
    name: 'MIT',
    rank: 1,
    baseUrl: 'https://www.eecs.mit.edu',
    country: 'USA',
    requiresResearch: false,
    projectPages: [
      'https://www.eecs.mit.edu/academics/undergraduate-programs/6-14-computer-science-economics-and-data-science/',
      'https://capstone.csail.mit.edu/',
      'https://www.eecs.mit.edu/academics/graduate-programs/meng-program/',
    ],
    selectors: {
      container: '.project-card, .capstone-item, article',
      title: 'h2, h3, .title',
      description: 'p, .description, .summary',
      techStack: '.tech-tags span, .technologies li',
      year: '.year, time, .date',
    },
  },
  {
    name: 'Stanford',
    rank: 2,
    baseUrl: 'https://cs.stanford.edu',
    country: 'USA',
    requiresResearch: false,
    projectPages: [
      'https://cs.stanford.edu/research/',
      'https://hci.stanford.edu/portfolio/',
      'https://ai.stanford.edu/projects/',
    ],
    selectors: {
      container: '.project, .research-item, .card',
      title: 'h2, h3, .title',
      description: 'p, .description',
      techStack: '.tech, .tools span',
      year: '.year, time',
    },
  },
  {
    name: 'Carnegie Mellon',
    rank: 3,
    baseUrl: 'https://www.cs.cmu.edu',
    country: 'USA',
    requiresResearch: false,
    projectPages: [
      'https://www.cs.cmu.edu/research',
      'https://www.csd.cs.cmu.edu/academics/bscs/capstone',
      'https://www.ri.cmu.edu/robotics-projects/',
    ],
    selectors: {
      container: '.research-item, .project, .node-teaser',
      title: 'h2, h3',
      description: 'p, .description',
      techStack: '.tech-tags',
      year: '.date, time',
    },
  },
  {
    name: 'UC Berkeley',
    rank: 4,
    baseUrl: 'https://eecs.berkeley.edu',
    country: 'USA',
    requiresResearch: false,
    projectPages: [
      'https://eecs.berkeley.edu/research',
      'https://www2.eecs.berkeley.edu/Students/Capstone/',
      'https://bair.berkeley.edu/projects/',
    ],
    selectors: {
      container: '.project, .research-area, .capstone-item',
      title: 'h2, h3, .title',
      description: 'p, .description',
      techStack: '.tech-list span',
      year: '.year, time',
    },
  },
  {
    name: 'Harvard',
    rank: 5,
    baseUrl: 'https://seas.harvard.edu',
    country: 'USA',
    requiresResearch: false,
    projectPages: [
      'https://seas.harvard.edu/computer-science',
      'https://seas.harvard.edu/research',
    ],
    selectors: {
      container: '.research-item, .card, .node',
      title: 'h2, h3',
      description: 'p, .description',
      techStack: '.tags',
      year: '.date',
    },
  },
  {
    name: 'Princeton',
    rank: 6,
    baseUrl: 'https://cs.princeton.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://cs.princeton.edu/research'],
    selectors: {
      container: '.research-area, .project',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'Cornell',
    rank: 7,
    baseUrl: 'https://cs.cornell.edu',
    country: 'USA',
    requiresResearch: false,
    projectPages: [
      'https://www.cs.cornell.edu/research',
      'https://www.cs.cornell.edu/undergrad/capstone',
    ],
    selectors: {
      container: '.research-item, .project',
      title: 'h2, h3, .title',
      description: 'p, .description',
    },
  },
  {
    name: 'UIUC',
    rank: 8,
    baseUrl: 'https://cs.illinois.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://cs.illinois.edu/research'],
    selectors: {
      container: '.research-area, .card',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'Georgia Tech',
    rank: 9,
    baseUrl: 'https://www.cc.gatech.edu',
    country: 'USA',
    requiresResearch: false,
    projectPages: [
      'https://www.cc.gatech.edu/research',
      'https://www.ic.gatech.edu/capstone-projects',
    ],
    selectors: {
      container: '.research-item, .project, .card',
      title: 'h2, h3, .title',
      description: 'p, .description',
      techStack: '.tech span',
    },
  },
  {
    name: 'University of Washington',
    rank: 10,
    baseUrl: 'https://cs.washington.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.washington.edu/research'],
    selectors: {
      container: '.research-project, .card',
      title: 'h2, h3',
      description: 'p',
    },
  },

  // ── 11–20 ──────────────────────────────────────────────────────────────
  {
    name: 'UT Austin',
    rank: 11,
    baseUrl: 'https://cs.utexas.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.utexas.edu/research'],
    selectors: {
      container: '.research-area, .node',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'Caltech',
    rank: 12,
    baseUrl: 'https://cms.caltech.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cms.caltech.edu/research'],
    selectors: {
      container: '.research-item, .project',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'University of Michigan',
    rank: 13,
    baseUrl: 'https://cse.umich.edu',
    country: 'USA',
    requiresResearch: false,
    projectPages: [
      'https://cse.umich.edu/research',
      'https://cse.umich.edu/eecs/capstone',
    ],
    selectors: {
      container: '.research-area, .project',
      title: 'h2, h3, .title',
      description: 'p, .description',
    },
  },
  {
    name: 'UCLA',
    rank: 14,
    baseUrl: 'https://cs.ucla.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.ucla.edu/research'],
    selectors: {
      container: '.research-area, .project',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'UCSD',
    rank: 15,
    baseUrl: 'https://cse.ucsd.edu',
    country: 'USA',
    requiresResearch: false,
    projectPages: [
      'https://cse.ucsd.edu/research',
      'https://cse.ucsd.edu/undergraduate/capstone',
    ],
    selectors: {
      container: '.research-area, .project',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'Purdue',
    rank: 16,
    baseUrl: 'https://cs.purdue.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.purdue.edu/research'],
    selectors: {
      container: '.research-area, .project',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'USC',
    rank: 17,
    baseUrl: 'https://cs.usc.edu',
    country: 'USA',
    requiresResearch: false,
    projectPages: [
      'https://www.cs.usc.edu/research',
      'https://viterbi.usc.edu/education/undergrad/capstone/',
    ],
    selectors: {
      container: '.research-item, .project',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'Columbia',
    rank: 18,
    baseUrl: 'https://cs.columbia.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.columbia.edu/research'],
    selectors: {
      container: '.research-area, .project',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'Yale',
    rank: 19,
    baseUrl: 'https://cpsc.yale.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://cpsc.yale.edu/research'],
    selectors: {
      container: '.research-area, .project',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'Duke',
    rank: 20,
    baseUrl: 'https://cs.duke.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.duke.edu/research'],
    selectors: {
      container: '.research-area, .project',
      title: 'h2, h3',
      description: 'p',
    },
  },

  // ── 21–40 ──────────────────────────────────────────────────────────────
  {
    name: 'University of Maryland',
    rank: 21,
    baseUrl: 'https://cs.umd.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.umd.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Toronto',
    rank: 22,
    baseUrl: 'https://web.cs.toronto.edu',
    country: 'Canada',
    requiresResearch: true,
    projectPages: ['https://web.cs.toronto.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'ETH Zurich',
    rank: 23,
    baseUrl: 'https://inf.ethz.ch',
    country: 'Switzerland',
    requiresResearch: false,
    projectPages: [
      'https://inf.ethz.ch/research.html',
      'https://www.systems.ethz.ch/research.html',
    ],
    selectors: {
      container: '.research-group, .project',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'University of Cambridge',
    rank: 24,
    baseUrl: 'https://cl.cam.ac.uk',
    country: 'UK',
    requiresResearch: true,
    projectPages: ['https://www.cl.cam.ac.uk/research/'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Oxford',
    rank: 25,
    baseUrl: 'https://cs.ox.ac.uk',
    country: 'UK',
    requiresResearch: true,
    projectPages: ['https://www.cs.ox.ac.uk/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of British Columbia',
    rank: 26,
    baseUrl: 'https://cs.ubc.ca',
    country: 'Canada',
    requiresResearch: true,
    projectPages: ['https://www.cs.ubc.ca/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Edinburgh',
    rank: 27,
    baseUrl: 'https://inf.ed.ac.uk',
    country: 'UK',
    requiresResearch: true,
    projectPages: ['https://www.inf.ed.ac.uk/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'NYU',
    rank: 28,
    baseUrl: 'https://cs.nyu.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://cs.nyu.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'UCSB',
    rank: 29,
    baseUrl: 'https://cs.ucsb.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.ucsb.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Chicago',
    rank: 30,
    baseUrl: 'https://cs.uchicago.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.uchicago.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Wisconsin Madison',
    rank: 31,
    baseUrl: 'https://cs.wisc.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.wisc.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Northwestern',
    rank: 32,
    baseUrl: 'https://mccormick.northwestern.edu/computer-science',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.mccormick.northwestern.edu/computer-science/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'UC Irvine',
    rank: 33,
    baseUrl: 'https://ics.uci.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.ics.uci.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Pennsylvania',
    rank: 34,
    baseUrl: 'https://www.cis.upenn.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cis.upenn.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Texas A&M',
    rank: 35,
    baseUrl: 'https://engineering.tamu.edu/cse',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://engineering.tamu.edu/cse/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Ohio State',
    rank: 36,
    baseUrl: 'https://cse.osu.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://cse.osu.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Virginia Tech',
    rank: 37,
    baseUrl: 'https://cs.vt.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://cs.vt.edu/research.html'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Minnesota',
    rank: 38,
    baseUrl: 'https://cs.umn.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.umn.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of California Davis',
    rank: 39,
    baseUrl: 'https://cs.ucdavis.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.ucdavis.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Michigan State',
    rank: 40,
    baseUrl: 'https://cse.msu.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cse.msu.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },

  // ── 41–60 ──────────────────────────────────────────────────────────────
  {
    name: 'University of Colorado Boulder',
    rank: 41,
    baseUrl: 'https://cs.colorado.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.colorado.edu/cs/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Rice University',
    rank: 42,
    baseUrl: 'https://cs.rice.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.rice.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Brown University',
    rank: 43,
    baseUrl: 'https://cs.brown.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://cs.brown.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Massachusetts Amherst',
    rank: 44,
    baseUrl: 'https://cs.umass.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cics.umass.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Johns Hopkins',
    rank: 45,
    baseUrl: 'https://cs.jhu.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.jhu.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Stony Brook',
    rank: 46,
    baseUrl: 'https://cs.stonybrook.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.stonybrook.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Penn State',
    rank: 47,
    baseUrl: 'https://cse.psu.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cse.psu.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Arizona State',
    rank: 48,
    baseUrl: 'https://cidse.engineering.asu.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://cidse.engineering.asu.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Pittsburgh',
    rank: 49,
    baseUrl: 'https://cs.pitt.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.pitt.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Rutgers',
    rank: 50,
    baseUrl: 'https://cs.rutgers.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.rutgers.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Virginia',
    rank: 51,
    baseUrl: 'https://engineering.virginia.edu/departments/computer-science',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://engineering.virginia.edu/departments/computer-science/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Utah',
    rank: 52,
    baseUrl: 'https://www.cs.utah.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.utah.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Boston University',
    rank: 53,
    baseUrl: 'https://bu.edu/cs',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.bu.edu/cs/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Northeastern',
    rank: 54,
    baseUrl: 'https://www.khoury.northeastern.edu',
    country: 'USA',
    requiresResearch: false,
    projectPages: ['https://www.khoury.northeastern.edu/research'],
    selectors: {
      container: '.research-area, .project',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'Dartmouth',
    rank: 55,
    baseUrl: 'https://cs.dartmouth.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.dartmouth.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Imperial College London',
    rank: 56,
    baseUrl: 'https://www.imperial.ac.uk/computing',
    country: 'UK',
    requiresResearch: true,
    projectPages: ['https://www.imperial.ac.uk/computing/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University College London',
    rank: 57,
    baseUrl: 'https://www.ucl.ac.uk/computer-science',
    country: 'UK',
    requiresResearch: true,
    projectPages: ['https://www.ucl.ac.uk/computer-science/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Waterloo',
    rank: 58,
    baseUrl: 'https://cs.uwaterloo.ca',
    country: 'Canada',
    requiresResearch: false,
    projectPages: [
      'https://cs.uwaterloo.ca/research',
      'https://uwaterloo.ca/computer-science/undergraduate/capstone-design-projects',
    ],
    selectors: {
      container: '.research-area, .project',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'Tsinghua University',
    rank: 59,
    baseUrl: 'https://www.cs.tsinghua.edu.cn',
    country: 'China',
    requiresResearch: true,
    projectPages: ['https://www.cs.tsinghua.edu.cn/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'National University of Singapore',
    rank: 60,
    baseUrl: 'https://www.comp.nus.edu.sg',
    country: 'Singapore',
    requiresResearch: true,
    projectPages: ['https://www.comp.nus.edu.sg/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },

  // ── 61–80 ──────────────────────────────────────────────────────────────
  {
    name: 'KAUST',
    rank: 61,
    baseUrl: 'https://www.kaust.edu.sa/computer-science',
    country: 'Saudi Arabia',
    requiresResearch: true,
    projectPages: ['https://www.kaust.edu.sa/computer-science'],
    selectors: {
      container: '.research-area, .project',
      title: 'h2, h3',
      description: 'p',
    },
  },
  {
    name: 'KFUPM',
    rank: 62,
    baseUrl: 'https://www.kfupm.edu.sa/departments/cs',
    country: 'Saudi Arabia',
    requiresResearch: true,
    projectPages: ['https://www.kfupm.edu.sa/departments/cs'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Tokyo',
    rank: 63,
    baseUrl: 'https://www.i.u-tokyo.ac.jp',
    country: 'Japan',
    requiresResearch: true,
    projectPages: ['https://www.i.u-tokyo.ac.jp/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'KAIST',
    rank: 64,
    baseUrl: 'https://cs.kaist.ac.kr',
    country: 'South Korea',
    requiresResearch: true,
    projectPages: ['https://cs.kaist.ac.kr/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'TU Delft',
    rank: 65,
    baseUrl: 'https://www.tudelft.nl/ewi/computer-science',
    country: 'Netherlands',
    requiresResearch: true,
    projectPages: ['https://www.tudelft.nl/ewi/computer-science/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Melbourne',
    rank: 66,
    baseUrl: 'https://cis.unimelb.edu.au',
    country: 'Australia',
    requiresResearch: true,
    projectPages: ['https://cis.unimelb.edu.au/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Texas Dallas',
    rank: 67,
    baseUrl: 'https://cs.utdallas.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://cs.utdallas.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Florida',
    rank: 68,
    baseUrl: 'https://www.cise.ufl.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cise.ufl.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of North Carolina Chapel Hill',
    rank: 69,
    baseUrl: 'https://cs.unc.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://cs.unc.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Arizona',
    rank: 70,
    baseUrl: 'https://cs.arizona.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.arizona.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Virginia',
    rank: 71,
    baseUrl: 'https://www.cs.virginia.edu',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.cs.virginia.edu/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Texas Arlington',
    rank: 72,
    baseUrl: 'https://www.uta.edu/academics/cs',
    country: 'USA',
    requiresResearch: true,
    projectPages: ['https://www.uta.edu/academics/cs/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Simon Fraser University',
    rank: 73,
    baseUrl: 'https://www.sfu.ca/computing',
    country: 'Canada',
    requiresResearch: true,
    projectPages: ['https://www.sfu.ca/computing/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Sydney',
    rank: 74,
    baseUrl: 'https://www.sydney.edu.au/computer-science',
    country: 'Australia',
    requiresResearch: true,
    projectPages: ['https://www.sydney.edu.au/computer-science/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of New South Wales',
    rank: 75,
    baseUrl: 'https://www.unsw.edu.au/engineering/computer-science',
    country: 'Australia',
    requiresResearch: true,
    projectPages: ['https://www.unsw.edu.au/engineering/computer-science/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Seoul National University',
    rank: 76,
    baseUrl: 'https://cse.snu.ac.kr',
    country: 'South Korea',
    requiresResearch: true,
    projectPages: ['https://cse.snu.ac.kr/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Hong Kong University of Science and Technology',
    rank: 77,
    baseUrl: 'https://www.cse.ust.hk',
    country: 'Hong Kong',
    requiresResearch: true,
    projectPages: ['https://www.cse.ust.hk/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Indian Institute of Technology Bombay',
    rank: 78,
    baseUrl: 'https://www.iitb.ac.in/cse',
    country: 'India',
    requiresResearch: true,
    projectPages: ['https://www.iitb.ac.in/cse/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Helsinki',
    rank: 79,
    baseUrl: 'https://www.helsinki.fi/en/computer-science',
    country: 'Finland',
    requiresResearch: true,
    projectPages: ['https://www.helsinki.fi/en/computer-science/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Copenhagen',
    rank: 80,
    baseUrl: 'https://di.ku.dk',
    country: 'Denmark',
    requiresResearch: true,
    projectPages: ['https://di.ku.dk/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },

  // ── 81–100 ──────────────────────────────────────────────────────────────
  {
    name: 'McMaster University',
    rank: 81,
    baseUrl: 'https://www.eng.mcmaster.ca/cas',
    country: 'Canada',
    requiresResearch: true,
    projectPages: ['https://www.eng.mcmaster.ca/cas/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Alberta',
    rank: 82,
    baseUrl: 'https://www.ualberta.ca/computing-science',
    country: 'Canada',
    requiresResearch: true,
    projectPages: ['https://www.ualberta.ca/computing-science/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Montreal',
    rank: 83,
    baseUrl: 'https://diro.umontreal.ca',
    country: 'Canada',
    requiresResearch: true,
    projectPages: ['https://diro.umontreal.ca/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Polytechnique Montreal',
    rank: 84,
    baseUrl: 'https://www.polymtl.ca/computer-software-engineering',
    country: 'Canada',
    requiresResearch: true,
    projectPages: ['https://www.polymtl.ca/computer-software-engineering/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'King Saud University',
    rank: 85,
    baseUrl: 'https://ccis.ksu.edu.sa',
    country: 'Saudi Arabia',
    requiresResearch: true,
    projectPages: ['https://ccis.ksu.edu.sa/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Sharjah',
    rank: 86,
    baseUrl: 'https://www.sharjah.ac.ae/en/academics/Colleges/csit',
    country: 'UAE',
    requiresResearch: true,
    projectPages: ['https://www.sharjah.ac.ae/en/academics/Colleges/csit'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Khalifa University',
    rank: 87,
    baseUrl: 'https://www.ku.ac.ae/college-of-computing',
    country: 'UAE',
    requiresResearch: true,
    projectPages: ['https://www.ku.ac.ae/college-of-computing'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Wollongong',
    rank: 88,
    baseUrl: 'https://www.uow.edu.au/engineering-information-sciences',
    country: 'Australia',
    requiresResearch: true,
    projectPages: ['https://www.uow.edu.au/engineering-information-sciences/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Auckland',
    rank: 89,
    baseUrl: 'https://www.cs.auckland.ac.nz',
    country: 'New Zealand',
    requiresResearch: true,
    projectPages: ['https://www.cs.auckland.ac.nz/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'York University',
    rank: 90,
    baseUrl: 'https://www.yorku.ca/laps/eecs',
    country: 'Canada',
    requiresResearch: true,
    projectPages: ['https://www.yorku.ca/laps/eecs/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Exeter',
    rank: 91,
    baseUrl: 'https://www.exeter.ac.uk/study/computer-science',
    country: 'UK',
    requiresResearch: true,
    projectPages: ['https://www.exeter.ac.uk/study/computer-science/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Bristol',
    rank: 92,
    baseUrl: 'https://www.bristol.ac.uk/engineering/computer-science',
    country: 'UK',
    requiresResearch: true,
    projectPages: ['https://www.bristol.ac.uk/engineering/computer-science/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Queen Mary University of London',
    rank: 93,
    baseUrl: 'https://www.qmul.ac.uk/eecs',
    country: 'UK',
    requiresResearch: true,
    projectPages: ['https://www.qmul.ac.uk/eecs/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Southampton',
    rank: 94,
    baseUrl: 'https://www.southampton.ac.uk/engineering/computer-science',
    country: 'UK',
    requiresResearch: true,
    projectPages: ['https://www.southampton.ac.uk/engineering/computer-science/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Nottingham',
    rank: 95,
    baseUrl: 'https://www.nottingham.ac.uk/computerscience',
    country: 'UK',
    requiresResearch: true,
    projectPages: ['https://www.nottingham.ac.uk/computerscience/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Glasgow',
    rank: 96,
    baseUrl: 'https://www.gla.ac.uk/schools/computing',
    country: 'UK',
    requiresResearch: true,
    projectPages: ['https://www.gla.ac.uk/schools/computing/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Mannheim',
    rank: 97,
    baseUrl: 'https://www.uni-mannheim.de/en/study/subjects/computer-science',
    country: 'Germany',
    requiresResearch: true,
    projectPages: ['https://www.uni-mannheim.de/en/study/subjects/computer-science/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'Technical University of Munich',
    rank: 98,
    baseUrl: 'https://www.in.tum.de/en',
    country: 'Germany',
    requiresResearch: true,
    projectPages: ['https://www.in.tum.de/en/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'University of Zurich',
    rank: 99,
    baseUrl: 'https://www.ifi.uzh.ch/en',
    country: 'Switzerland',
    requiresResearch: true,
    projectPages: ['https://www.ifi.uzh.ch/en/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
  {
    name: 'RMIT University',
    rank: 100,
    baseUrl: 'https://www.rmit.edu.au/computer-science',
    country: 'Australia',
    requiresResearch: true,
    projectPages: ['https://www.rmit.edu.au/computer-science/research'],
    selectors: { container: '.research-area', title: 'h2, h3', description: 'p' },
  },
];

/**
 * Convenience accessors
 */

/** Get all universities that have known project pages (not requiresResearch) */
export function getResolvedSources(): UniversitySource[] {
  return UNIVERSITY_SOURCES.filter((s) => !s.requiresResearch);
}

/** Get universities still needing manual research */
export function getUnresolvedSources(): UniversitySource[] {
  return UNIVERSITY_SOURCES.filter((s) => s.requiresResearch);
}

/** Get a single source by name (case-insensitive) */
export function getSourceByName(name: string): UniversitySource | undefined {
  return UNIVERSITY_SOURCES.find(
    (s) => s.name.toLowerCase() === name.toLowerCase(),
  );
}
